source "https://rubygems.org"

gem "rails", "5.0.0.rc1"
gem "sprockets", "~> 4.x"
gem "sass-rails", "~> 6.x"
gem "babel-schmooze-sprockets", path: "../.."

gem "puma"
gem "uglifier", ">= 1.3.0"
gem "pry-meta"

source "https://rails-assets.org" do
  gem "rails-assets-react"
end
