source "https://rubygems.org"

gem "rails", github: "rails/rails"

gem "puma"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "sprockets", github: "rails/sprockets", branch: "master"
gem "sass-rails", github: "rails/sass-rails", branch: "master"
gem "pry-meta"
gem "babel-schmooze-sprockets", path: "../.."
